version: 1
description: ""
parallel: 2
properties:
  auto_dependency: true
jobs:
- csv_to_json:
    job_parameters:
      param1: "value1"
      param2: "value2"
    retry_properties:
      max_retry: 2
      retry_interval: 10
      retry_status:
      - "FAILED"
- csv_to_json_copy1:
    job_parameters:
      param3: "value3"
- csv_to_json_copy2:
    job_parameters:
      param4: "value4"
- "csv_to_json_copy3"
- "csv_to_json_copy4"
- "csv_to_hive_users2"
