version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- csv_to_hive_users2:
    spark_properties:
      spark_version: "10.1.x-scala2.12"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users3"
    spark_properties:
      cluster_id: "0228-044814-pdvpv8h3"
- "hive_to_hive_users4"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users4"
- "hive_to_hive_users5"
- "csv_to_hive_users4"
spark_properties:
  spark_version: "10.4.x-scala2.12"
folder: "/guzzle_pipeline"
