version: 1
description: ""
parallel: 2
properties:
  auto_dependency: true
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- csv_to_hive:
    job_parameters:
      source: "users2.csv"
      target: "users2"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users3"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users4"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users4"
- "csv_to_json_copy4"
- "csv_to_hive_users2"
folder: "/guzzle_pipeline"
