version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
    retry_properties:
      max_retry: 2
      retry_interval: 10
      retry_status:
      - "FAILED"
- "csv_to_hive_users2"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users3"
- "hive_to_hive_users4"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users4"
- "hive_to_hive_users5"
- "csv_to_hive_users4"
folder: "/guzzle_pipeline"
