version: 1
description: ""
parallel: 2
properties:
  auto_dependency: true
jobs:
- csv_to_json:
    job_parameters:
      source: "users1.csv"
      target: "users"
- csv_to_json:
    job_parameters:
      source: "users2.csv"
      target: "users2"
- csv_to_json_copy1:
    job_parameters:
      param3: "value3"
- csv_to_json_copy2:
    job_parameters:
      param4: "value4"
- "csv_to_json_copy3"
- "csv_to_json_copy4"
- "csv_to_hive_users2"
folder: "/guzzle_pipeline"
