version: 1
description: ""
parallel: 10
properties:
  auto_dependency: false
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- "csv_to_hive_users2"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users3"
- "hive_to_hive_users4"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users4"
- "hive_to_hive_users5"
- "csv_to_hive_users4"
folder: "/guzzle_pipeline"
