version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- "csv_to_hive"
- csv_to_hive:
    job_parameters:
      target: "users3"
- csv_to_hive:
    job_parameters:
      source: "users2.csv"
      target: "users4"
folder: "/guzzle_pipeline"
