version: 1
description: ""
parallel: 1
properties:
  auto_dependency: true
  pipeline_type: "databricks_multitask"
jobs:
- csv_to_hive:
    job_parameters:
      target: "users"
    spark_properties:
      job_compute_key: "compute_1"
- hive_to_hive_users4:
    spark_properties:
      job_compute_key: "compute_2"
computes:
- name: "compute_1"
  properties:
    spark_version: "10.4.x-scala2.12"
    workers:
      num_workers: "1"
    instance_pool_id: "${cluster_pool_id}"
- name: "compute_2"
  properties:
    spark_version: "9.1.x-scala2.12"
    driver_node_type_id: "Standard_DS3_v2"
    node_type_id: "Standard_DS3_v2"
    workers:
      num_workers: "1"
spark_properties: {}
folder: "/multitask_pipeline"
