version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
  pipeline_type: "databricks_multitask"
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- hive_to_hive_users5: {}
- "hive_to_hive_users4"
spark_properties:
  spark_version: "10.4.x-scala2.12"
folder: "/multitask_pipeline"
