version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
  pipeline_type: "databricks_multitask"
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- csv_to_hive_users2: {}
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users3"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users4"
- "hive_to_hive_users5"
- "hive_to_hive_users4"
folder: "/multitask_pipeline"
