version: 1
description: ""
parallel: 1
properties:
  auto_dependency: true
  pipeline_type: "databricks_multitask"
jobs:
- csv_to_hive:
    job_parameters:
      source: "users1.csv"
      target: "users"
- hive_to_hive_users5: {}
- hive_to_hive_users4:
    retry_properties:
      max_retry: 3
      retry_interval: 30
      retry_status:
      - "FAILED"
- "csv_to_hive_users2"
spark_properties: {}
folder: "/multitask_pipeline"
