version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- csv_to_hive:
    job_parameters:
      source: "users2.csvxx"
      target: "users"
- hive_to_hive:
    job_parameters:
      source: "users"
      target: "users2"
