version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- csv_to_json:
    job_parameters:
      param1: "value1"
      param2: "value2"
- csv_to_json_copy2:
    job_parameters:
      param3: "value3"
