version: 1
description: ""
parallel: 1
properties:
  auto_dependency: false
jobs:
- csv_to_json:
    job_parameters:
      param1: "value1"
      param2: "value2"
    spark_properties:
      job_cluster_key: "shared-cluster"
- csv_to_json_copy2:
    job_parameters:
      param3: "value3"
    spark_properties:
      driver_node_type_id: "Standard_DS3_v2"
      node_type_id: "Standard_DS3_v2"
      spark_conf:
        sconfig1": "svalue1"
        sconfig2": "svalue2"
      spark_version: "apache-spark-2.4.x-scala2.11"
      workers:
        autoscale:
          max_workers: "8"
          min_workers: "1"
- csv_to_json_copy1:
    job_parameters:
      param4: "value4"
    spark_properties:
      driver_node_type_id: "Standard_DS3_v2"
      node_type_id: "Standard_DS3_v2"
      spark_conf:
        sconfig1": "svalue1"
        sconfig2": "svalue2"
      spark_version: "apache-spark-2.4.x-scala2.11"
      workers:
        autoscale:
          max_workers: "8"
          min_workers: "1"
- local_csv_to_json:
    job_parameters:
      param5: "value5"
    spark_properties:
      cluster_id: "existing-cluste-1"
- processing_test:
    job_parameters:
      param6: "value6"
