version: 1
description: ""
parallel: 3
properties:
  auto_dependency: true
jobs:
- csv_to_hive:
    job_parameters:
      source: "employee.csv"
      target: "users1"
- csv_to_hive:
    job_parameters:
      source: "employee.csv"
      target: "users2"
- "hive_to_hive_users4"
- hive_to_hive_users5:
    job_parameters: {}
- csv_to_hive:
    job_parameters:
      source: "employee.csv"
      target: "users3"
- csv_to_hive:
    job_parameters:
      source: "employee.csv"
      target: "users4"
- hive_to_hive:
    job_parameters:
      source: "users2"
      target: "users5"
- hive_to_hive:
    job_parameters:
      source: "users3"
      target: "users6"
folder: "/dependency_test"
